### ISSUE TITLE
JS port

### ISSUE THREAD

**Issue by benjamingr** [alexflint/go-restructure#4]
Hey, I made a quick JS port at https://github.com/benjamingr/js-restructure

I'll add nested properties and other goodies later. Gave you credit and all :) 

Just a quick fun experiment while my code was compiling and I was angry at having no internet - nothing serious.

**Comment by alexflint** [comment]
Nice. It's very succinct in javascript!

**Comment by benjamingr** [comment]
Thanks for the idea by the way!

Feel free to close whenever you want. I added tests and regression and published on NPM. If you have any ideas/feedback let me know.

**Comment by alexflint** [comment]
Cool man, nice work. All the best!
