### ISSUE TITLE
Example with email address

### ISSUE THREAD

**Issue by sethgrid** [alexflint/go-restructure#5]
I think this is a super useful library. Consider changing the example or putting a note that regex should not be used to validate an email address. In [section 6.1 of rfc822](https://www.ietf.org/rfc/rfc0822.txt), it goes a little into this suggesting that the best you can do is `local-part@domain` in that `domain` only optionally has a `.`. I work with a large email service provider, and the best you can do to validate an email is to send to it. Inevitably, any regex will fail aside from "does it have an at-sign?". Cheers!

**Comment by alexflint** [comment]
Thanks, yeah I completely agree.

**Comment by alexflint** [comment]
Resolved by #8
